// JSDemos/Demos/ActionSheet/Basics/Angular/app/app.component.ts
import { NgModule, Component, enableProdMode } from "@angular/core";
import { BrowserModule } from "@angular/platform-browser";
import { platformBrowserDynamic } from "@angular/platform-browser-dynamic";

import { DxActionSheetModule, DxButtonModule, DxSwitchModule } from "devextreme-angular";
import notify from "devextreme/ui/notify";

if (!/localhost/.test(document.location.host)) {
  enableProdMode();
}

@Component({
  selector: "demo-app",
  templateUrl: "app/app.component.html",
  styleUrls: ["app/app.component.css"],
})
export class AppComponent {
  commands: any[] = [
    { text: "Call" },
    { text: "Send message" },
    { text: "Edit" },
    { text: "Delete" },
  ];

  showNotify(value) {
    notify(`The "${value}" button is clicked.`);
  }
}

@NgModule({
  imports: [
    BrowserModule,
    DxActionSheetModule,
    DxButtonModule,
    DxSwitchModule,
  ],
  declarations: [AppComponent],
  bootstrap: [AppComponent],
})
export class AppModule { }

platformBrowserDynamic().bootstrapModule(AppModule);

<dx-action-sheet
  #actionSheet
  title="Choose action"
  [items]="commands"
  [visible]="false"
  [showTitle]="true"
  [showCancelButton]="true"
  (onCancelClick)="showNotify("Cancel")"
  (onItemClick)="showNotify($event.itemData.text)"
>
</dx-action-sheet>
<dx-button
  class="button"
  text="Click to show Action Sheet"
  (onClick)="actionSheet.visible = true"
></dx-button>
<div class="options">
  <div class="caption">Options</div>
  <div class="option">
    <span>Show title</span>
    <dx-switch [(value)]="actionSheet.showTitle"></dx-switch>
  </div>
  <div class="option">
    <span>Show cancel button</span>
    <dx-switch [(value)]="actionSheet.showCancelButton"></dx-switch>
  </div>
</div>

// JSDemos/Demos/ActionSheet/Basics/React/App.js
import React from "react";
import ActionSheet from "devextreme-react/action-sheet";
import Button from "devextreme-react/button";
import Switch from "devextreme-react/switch";
import notify from "devextreme/ui/notify";
import { actionSheetItems } from "./data.js";

class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      isActionSheetVisible: false,
      showTitle: true,
      showCancelButton: true,
    };

    this.showActionSheet = this.showActionSheet.bind(this);
    this.onActionSheetItemClick = this.onActionSheetItemClick.bind(this);
    this.onActionSheetCancelClick = this.onActionSheetCancelClick.bind(this);
    this.onActionSheetButtonClick = this.onActionSheetButtonClick.bind(this);
    this.changeTitle = this.changeTitle.bind(this);
    this.changeCancelButton = this.changeCancelButton.bind(this);
  }

  render() {
    return (
      <div>
        <ActionSheet
          dataSource={actionSheetItems}
          title="Choose action"
          showTitle={this.state.showTitle}
          showCancelButton={this.state.showCancelButton}
          visible={this.state.isActionSheetVisible}
          onItemClick={this.onActionSheetItemClick}
          onCancelClick={this.onActionSheetCancelClick} />
        <div className="button">
          <Button width="100%" text="Click to show Action Sheet" onClick={this.showActionSheet} />
        </div>
        <div className="options">
          <div className="caption">Options</div>
          <div className="option">
            <span>Show title</span>
            <Switch value={this.state.showTitle} onValueChanged={this.changeTitle} />
          </div>
          <div className="option">
            <span>Show cancel button</span>
            <Switch value={this.state.showCancelButton} onValueChanged={this.changeCancelButton} />
          </div>
        </div>
      </div>
    );
  }

  showActionSheet() {
    this.setState({
      isActionSheetVisible: true,
    });
  }

  onActionSheetItemClick(e) {
    this.onActionSheetButtonClick(e.itemData.text);
  }

  onActionSheetCancelClick() {
    this.onActionSheetButtonClick("Cancel");
  }

  onActionSheetButtonClick(buttonName) {
    this.setState({
      isActionSheetVisible: false,
    });
    notify(`The "${buttonName}" button is clicked.`);
  }

  changeTitle(e) {
    this.setState({
      showTitle: e.value,
    });
  }

  changeCancelButton(e) {
    this.setState({
      showCancelButton: e.value,
    });
  }
}

export default App;
