// JSDemos/Demos/ButtonGroup/Overview/React/App.js
import React from "react";
import { ButtonGroup } from "devextreme-react/button-group";
import notify from "devextreme/ui/notify";
import { alignments, fontStyles } from "./data.js";

const selectedItemKeys = ["left"];

class App extends React.Component {
  render() {
    return (
      <div>
        <div className="buttongroups-container">
          <ButtonGroup
            items={alignments}
            keyExpr="alignment"
            stylingMode="outlined"
            selectedItemKeys={selectedItemKeys}
            onItemClick={itemClick}
          />
          <ButtonGroup
            items={fontStyles}
            keyExpr="style"
            stylingMode="outlined"
            selectionMode="multiple"
            onItemClick={itemClick}
          />
        </div>
        <div className="buttongroups-container">
          <ButtonGroup
            items={alignments}
            keyExpr="alignment"
            stylingMode="text"
            selectedItemKeys={selectedItemKeys}
            onItemClick={itemClick}
          />
          <ButtonGroup
            className="multiple-selection-styling-mode"
            items={fontStyles}
            keyExpr="style"
            stylingMode="text"
            selectionMode="multiple"
            onItemClick={itemClick}
          />
        </div>
      </div>
    );
  }
}

function itemClick(e) {
  notify({ message: `The "${e.itemData.hint}" button was clicked`, width: 320 }, "success", 1000);
}

export default App;

// JSDemos/Demos/ButtonGroup/Overview/Vue/App.vue
<template>
  <div>
    <div class="buttongroups-container">
      <DxButtonGroup
        :items="alignments"
        :selected-item-keys="["left"]"
        key-expr="alignment"
        styling-mode="outlined"
        @item-click="itemClick"
      />
      <DxButtonGroup
        :items="fontStyles"
        key-expr="style"
        styling-mode="outlined"
        selection-mode="multiple"
        @item-click="itemClick"
      />
    </div>
    <div class="buttongroups-container">
      <DxButtonGroup
        :items="alignments"
        :selected-item-keys="["left"]"
        key-expr="alignment"
        styling-mode="text"
        @item-click="itemClick"
      />
      <DxButtonGroup
        :items="fontStyles"
        class="multiple-selection-styling-mode"
        key-expr="style"
        styling-mode="text"
        selection-mode="multiple"
        @item-click="itemClick"
      />
    </div>
  </div>
</template>
<script>
import DxButtonGroup from "devextreme-vue/button-group";
import notify from "devextreme/ui/notify";
import { alignments, fontStyles } from "./data.js";

export default {
  components: {
    DxButtonGroup,
  },
  data() {
    return {
      alignments,
      fontStyles,
    };
  },
  methods: {
    itemClick(e) {
      notify({ message: `The "${e.itemData.hint}" button was clicked`, width: 320 }, "success", 1000);
    },
  },
};
</script>
<style scoped>
  .buttongroups-container {
    display: flex;
    justify-content: center;
    font-size: 16px;
  }

  .buttongroups-container > div {
    padding: 0 12px;
  }

  .buttongroups-container:first-child {
    margin-top: 120px;
    margin-bottom: 40px;
  }

  .multiple-selection-styling-mode {
    border-left-width: 1px;
    border-left-style: solid;
    border-color: #ddd;
  }
</style>
