// JSDemos/Demos/ButtonGroup/Overview/React/App.js
import React from "react";
import { ButtonGroup } from "devextreme-react/button-group";
import notify from "devextreme/ui/notify";
import { alignments, fontStyles } from "./data.js";

const selectedItemKeys = ["left"];

class App extends React.Component {
  render() {
    return (
      <div>
        <div className="buttongroups-container">
          <ButtonGroup
            items={alignments}
            keyExpr="alignment"
            stylingMode="outlined"
            selectedItemKeys={selectedItemKeys}
            onItemClick={itemClick}
          />
          <ButtonGroup
            items={fontStyles}
            keyExpr="style"
            stylingMode="outlined"
            selectionMode="multiple"
            onItemClick={itemClick}
          />
        </div>
        <div className="buttongroups-container">
          <ButtonGroup
            items={alignments}
            keyExpr="alignment"
            stylingMode="text"
            selectedItemKeys={selectedItemKeys}
            onItemClick={itemClick}
          />
          <ButtonGroup
            className="multiple-selection-styling-mode"
            items={fontStyles}
            keyExpr="style"
            stylingMode="text"
            selectionMode="multiple"
            onItemClick={itemClick}
          />
        </div>
      </div>
    );
  }
}

function itemClick(e) {
  notify({ message: `The "${e.itemData.hint}" button was clicked`, width: 320 }, "success", 1000);
}

export default App;

// JSDemos/Demos/ButtonGroup/Overview/Angular/app/app.component.ts
import { Component, NgModule, enableProdMode } from "@angular/core";
import { BrowserModule } from "@angular/platform-browser";
import { platformBrowserDynamic } from "@angular/platform-browser-dynamic";
import { DxButtonGroupModule } from "devextreme-angular";
import notify from "devextreme/ui/notify";

import { Alignment, FontStyle, Service } from "./app.service";

if (!/localhost/.test(document.location.host)) {
  enableProdMode();
}

@Component({
  selector: "demo-app",
  providers: [Service],
  templateUrl: "app/app.component.html",
  styleUrls: ["app/app.component.css"],
  preserveWhitespaces: true,
})

export class AppComponent {
  alignments: Alignment[];

  fontStyles: FontStyle[];

  constructor(service: Service) {
    this.alignments = service.getAlignments();
    this.fontStyles = service.getFontStyles();
  }

  itemClick(e) {
    notify({ message: `The "${e.itemData.hint}" button was clicked`, width: 320 }, "success", 1000);
  }
}

@NgModule({
  imports: [
    BrowserModule,
    DxButtonGroupModule,
  ],
  declarations: [AppComponent],
  bootstrap: [AppComponent],
})

export class AppModule { }

platformBrowserDynamic().bootstrapModule(AppModule);

<div class="buttongroups-container">
  <dx-button-group
    [items]="alignments"
    keyExpr="alignment"
    stylingMode="outlined"
    [selectedItemKeys]="["left"]"
    (onItemClick)="itemClick($event)"
  >
  </dx-button-group>
  <dx-button-group
    [items]="fontStyles"
    keyExpr="style"
    stylingMode="outlined"
    selectionMode="multiple"
    (onItemClick)="itemClick($event)"
  >
  </dx-button-group>
</div>
<div class="buttongroups-container">
  <dx-button-group
    [items]="alignments"
    keyExpr="alignment"
    stylingMode="text"
    [selectedItemKeys]="["left"]"
    (onItemClick)="itemClick($event)"
  >
  </dx-button-group>
  <dx-button-group
    class="multiple-selection-styling-mode"
    [items]="fontStyles"
    keyExpr="style"
    stylingMode="text"
    selectionMode="multiple"
    (onItemClick)="itemClick($event)"
  >
  </dx-button-group>
</div>
