// JSDemos/Demos/Autocomplete/Overview/React/App.js
import React from "react";

import OData from "devextreme/data/odata/store";
import { Autocomplete } from "devextreme-react/autocomplete";
import CustomStore from "devextreme/data/custom_store";
import "whatwg-fetch";

import {
  names, surnames, positions,
} from "./data.js";

function isNotEmpty(value) {
  return value !== undefined && value !== null && value !== "";
}

const states = new OData({
  url: "https://js.devexpress.com/Demos/DevAV/odata/States?$select=Sate_ID,State_Long,State_Short",
  key: "Sate_ID",
  keyType: "Int32",
});

const clientsStore = new CustomStore({
  key: "Value",
  useDefaultSearch: true,
  load(loadOptions) {
    let params = "?";
    [
      "skip",
      "take",
      "filter",
    ].forEach((option) => {
      if (option in loadOptions && isNotEmpty(loadOptions[option])) {
        params += `${option}=${JSON.stringify(loadOptions[option])}&`;
      }
    });
    params = params.slice(0, -1);
    return fetch(`https://js.devexpress.com/Demos/Mvc/api/DataGridWebApi/CustomersLookup${params}`)
      .then((response) => response.json())
      .then((data) => ({
        data: data.data,
      }))
      .catch(() => { throw new Error("Data Loading Error"); });
  },
});

class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      firstName: "",
      lastName: "",
      position: positions[0],
      state: "",
      currentClient: "",
    };

    this.handleFirstNameChange = this.handleFirstNameChange.bind(this);
    this.handleLastNameChange = this.handleLastNameChange.bind(this);
    this.handleStateChange = this.handleStateChange.bind(this);
    this.handleCurrentClientChange = this.handleCurrentClientChange.bind(this);
  }

  render() {
    let fullInfo = "";
    fullInfo += (`${this.state.firstName || ""} ${this.state.lastName || ""}`).trim();
    fullInfo += (fullInfo && this.state.position) ? (`, ${this.state.position}`) : this.state.position || "";
    fullInfo += (fullInfo && this.state.state) ? (`, ${this.state.state}`) : this.state.state || "";
    fullInfo += (fullInfo && this.state.currentClient) ? (`, ${this.state.currentClient}`) : this.state.currentClient || "";

    return (
      <div className="form">

        <div className="dx-fieldset">
          <div className="dx-fieldset-header">Default Mode</div>
          <div className="dx-field">
            <div className="dx-field-label">First Name</div>
            <div className="dx-field-value">
              <Autocomplete
                dataSource={names}
                value={this.state.firstName}
                onValueChanged={this.handleFirstNameChange}
                placeholder="Type first name..."
              />
            </div>
          </div>
        </div>

        <div className="dx-fieldset">
          <div className="dx-fieldset-header">With Clear Button</div>
          <div className="dx-field">
            <div className="dx-field-label">Last Name</div>
            <div className="dx-field-value">
              <Autocomplete
                dataSource={surnames}
                value={this.state.lastName}
                onValueChanged={this.handleLastNameChange}
                showClearButton={true}
                placeholder="Type last name..."
              />
            </div>
          </div>
        </div>

        <div className="dx-fieldset">
          <div className="dx-fieldset-header">Disabled</div>
          <div className="dx-field">
            <div className="dx-field-label">Position</div>
            <div className="dx-field-value">
              <Autocomplete
                dataSource={positions}
                value={this.state.position}
                disabled={true}
              />
            </div>
          </div>
        </div>

        <div className="dx-fieldset">
          <div className="dx-fieldset-header">Custom Item Template and Data Source Usage</div>
          <div className="dx-field">
            <div className="dx-field-label">State</div>
            <div className="dx-field-value">
              <Autocomplete
                dataSource={states}
                value={this.state.state}
                valueExpr="State_Long"
                onValueChanged={this.handleStateChange}
                placeholder="Type state name..."
                itemRender={this.renderState}
              />
            </div>
          </div>
        </div>

        <div className="dx-fieldset">
          <div className="dx-fieldset-header">With Custom Store and Search Options</div>
          <div className="dx-field">
            <div className="dx-field-label">Current Client</div>
            <div className="dx-field-value">
              <Autocomplete
                dataSource={clientsStore}
                value={this.state.currentClient}
                valueExpr="Text"
                onValueChanged={this.handleCurrentClientChange}
                minSearchLength={2}
                searchTimeout={500}
                placeholder="Type client name..."
              />
            </div>
          </div>
        </div>

        <div className="dx-fieldset">
          <div className="dx-fieldset-header">Event Handling</div>
          <div className="employees-data">
            Employee data: <span>{fullInfo}</span>
          </div>
        </div>
      </div>
    );
  }

  renderState(data) {
    return <span>{data.State_Long} ({data.State_Short})</span>;
  }

  handleFirstNameChange(e) {
    this.setState({
      firstName: e.value,
    });
  }

  handleLastNameChange(e) {
    this.setState({
      lastName: e.value,
    });
  }

  handleStateChange(e) {
    this.setState({
      state: e.value,
    });
  }

  handleCurrentClientChange(e) {
    this.setState({
      currentClient: e.value,
    });
  }
}

export default App;

// JSDemos/Demos/Autocomplete/Overview/Angular/app/app.component.ts
import { Component, NgModule, enableProdMode } from "@angular/core";
import { BrowserModule } from "@angular/platform-browser";
import { platformBrowserDynamic } from "@angular/platform-browser-dynamic";
import { HttpClient, HttpClientModule, HttpParams } from "@angular/common/http";
import { lastValueFrom } from "rxjs";

import { DxAutocompleteModule, DxTemplateModule } from "devextreme-angular";
import data from "devextreme/data/odata/store";
import CustomStore from "devextreme/data/custom_store";

import { Service } from "./app.service";

if (!/localhost/.test(document.location.host)) {
  enableProdMode();
}

function isNotEmpty(value: any): boolean {
  return value !== undefined && value !== null && value !== "";
}

@Component({
  selector: "demo-app",
  providers: [Service],
  templateUrl: "app/app.component.html",
  styleUrls: ["app/app.component.css"],
})

export class AppComponent {
  names: string[];

  surnames: string[];

  positions: string[];

  states: any;

  clientsStore: CustomStore;

  firstName = "";

  lastName = "";

  position: string;

  state = "";

  currentClient = "";

  fullInfo = "";

  constructor(httpClient: HttpClient, service: Service) {
    this.clientsStore = new CustomStore({
      key: "Value",
      useDefaultSearch: true,
      load(loadOptions: any) {
        let params: HttpParams = new HttpParams();
        [
          "skip",
          "take",
          "filter",
        ].forEach((option) => {
          if (option in loadOptions && isNotEmpty(loadOptions[option])) {
            params = params.set(option, JSON.stringify(loadOptions[option]));
          }
        });
        return lastValueFrom(httpClient.get("https://js.devexpress.com/Demos/Mvc/api/DataGridWebApi/CustomersLookup", { params }))
          .then((data: any) => ({
            data: data.data,
          }))
          .catch((error) => { throw "Data Loading Error"; });
      },
    });
    this.states = new data({
      url: "https://js.devexpress.com/Demos/DevAV/odata/States?$select=Sate_ID,State_Long,State_Short",
      key: "Sate_ID",
      keyType: "Int32",
    });
    this.names = service.getNames();
    this.surnames = service.getSurnames();
    this.positions = service.getPositions();
    this.position = this.positions[0];
  }

  updateEmployeeInfo() {
    let result = "";
    result += (`${this.firstName || ""} ${this.lastName || ""}`).trim();
    result += (result && this.position) ? (`, ${this.position}`) : this.position || "";
    result += (result && this.state) ? (`, ${this.state}`) : this.state || "";
    result += (result && this.currentClient) ? (`, ${this.currentClient}`) : this.currentClient || "";
    this.fullInfo = result;
  }
}

@NgModule({
  imports: [
    BrowserModule,
    DxAutocompleteModule,
    DxTemplateModule,
    HttpClientModule,
  ],
  declarations: [AppComponent],
  bootstrap: [AppComponent],
})

export class AppModule { }

platformBrowserDynamic().bootstrapModule(AppModule);

<div class="form">
  <div class="dx-fieldset">
    <div class="dx-fieldset-header">Default Mode</div>
    <div class="dx-field">
      <div class="dx-field-label">First Name</div>
      <div class="dx-field-value">
        <dx-autocomplete
          placeholder="Type first name..."
          [(value)]="firstName"
          [dataSource]="names"
          (onValueChanged)="updateEmployeeInfo($event)"
        >
        </dx-autocomplete>
      </div>
    </div>
  </div>
  <div class="dx-fieldset">
    <div class="dx-fieldset-header">With Clear Button</div>
    <div class="dx-field">
      <div class="dx-field-label">Last Name</div>
      <div class="dx-field-value">
        <dx-autocomplete
          placeholder="Type last name..."
          [showClearButton]="true"
          [dataSource]="surnames"
          [(value)]="lastName"
          (onValueChanged)="updateEmployeeInfo($event)"
        >
        </dx-autocomplete>
      </div>
    </div>
  </div>
  <div class="dx-fieldset">
    <div class="dx-fieldset-header">Disabled</div>
    <div class="dx-field">
      <div class="dx-field-label">Position</div>
      <div class="dx-field-value">
        <dx-autocomplete
          [disabled]="true"
          [value]="position"
          [dataSource]="positions"
        >
        </dx-autocomplete>
      </div>
    </div>
  </div>
  <div class="dx-fieldset">
    <div class="dx-fieldset-header"
      >Custom Item Template and Data Source Usage</div
    >
    <div class="dx-field">
      <div class="dx-field-label">State</div>
      <div class="dx-field-value">
        <dx-autocomplete
          placeholder="Type state name..."
          valueExpr="State_Long"
          [dataSource]="states"
          [(value)]="state"
          (onValueChanged)="updateEmployeeInfo($event)"
        >
          <div *dxTemplate="let item of "item"">
            <span>{{ item.State_Long }} ({{ item.State_Short }})</span>
          </div>
        </dx-autocomplete>
      </div>
    </div>
  </div>
  <div class="dx-fieldset">
    <div class="dx-fieldset-header">With Custom Store and Search Options</div>
    <div class="dx-field">
      <div class="dx-field-label">Current Client</div>
      <div class="dx-field-value">
        <dx-autocomplete
          placeholder="Type client name..."
          [minSearchLength]="2"
          [searchTimeout]="500"
          valueExpr="Text"
          [dataSource]="clientsStore"
          [(value)]="currentClient"
          (onValueChanged)="updateEmployeeInfo($event)"
        >
        </dx-autocomplete>
      </div>
    </div>
  </div>
  <div class="dx-fieldset">
    <div class="dx-fieldset-header">Event Handling</div>
    <div class="employees-data">
      Employee data: <span>{{ fullInfo }}</span>
    </div>
  </div>
</div>
